version: 1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      - restore_cache:
          keys: sbt-cache

      - run:
          name: Compile dist package
          command: cat /dev/null | ./sbt compile

      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

      - run:
          name: Test
          command: cat /dev/null | ./sbt test:test
