version: 1
jobs:
  build:
    docker:
      - image: hseeberger/scala-sbt:8u131-jdk_2.12.2_0.13.15

    steps:
      - checkout
      - run:
          name: Compile dist package
          command: cat /dev/null | sbt clean update dist
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - run:
          name: Test
          command: cat /dev/null | sbt test:test
