version: 1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      - restore_cache:
          keys:
            - sbt-{{ checksum "build.sbt" }}

      - run:
          name: Compile dist package
          command: cat /dev/null | sbt compile

      - save_cache:
          key: sbt-{{ checksum "build.sbt" }}
          paths:
            - "~/.ivy2"

      - run:
          name: Test
          command: cat /dev/null | sbt test:test
